---
- name: Set facts
  ansible.builtin.set_fact:
    client_ssh_public_key_path: "{{ ansible_env.HOME }}/.ssh/id_ed25519_rpi.pub"
    client_ssh_private_key_path: "{{ ansible_env.HOME }}/.ssh/id_ed25519_rpi"

- name: Extend .ssh/config with SSH identity
  community.general.ssh_config:
    host: "raspberrypi.local"
    hostname: "raspberrypi.local"
    user: "{{ ansible_env.USER }}"
    identity_file: "{{ client_ssh_private_key_path }}"
    state: present
