---
- name: Extend .ssh/config with SSH identity
  community.general.ssh_config:
    host: "raspberrypi.local"
    hostname: "raspberrypi.local"
    user: "{{ ansible_env.USER }}"
    identity_file: "{{ peer_ssh_private_key }}"
    state: present

- name: Copy zettelkasten-push systemd service
  ansible.builtin.template:
    src: zettelkasten-git-sync.service
    dest: "{{ ansible_env.HOME}}/.config/systemd/user/zettelkasten-git-sync.service"

- name: Copy zettelkasten-git-sync systemd timer
  ansible.builtin.copy:
    src: zettelkasten-git-sync.timer
    dest: "{{ ansible_env.HOME}}/.config/systemd/user/zettelkasten-git-sync.timer"

- name: Enable systemd timer for periodic backups
  ansible.builtin.systemd_service:
    name: zettelkasten-git-sync.timer
    scope: user
    enabled: true
    state: started
