---
- name: Set authorized key taken from file
  become: true
  ansible.posix.authorized_key:
    user: git
    state: present
    key: "{{ lookup('file', hostvars['localhost']['client_ssh_public_key_path']) }}"
