---
- name: Install unison for x86_64
  block:
    - name: Install unison for x86_64
      ansible.builtin.unarchive:
        src: "https://github.com/bcpierce00/unison/releases/download/v{{ package.unison.version }}/unison-{{ package.unison.version }}-ubuntu-x86_64.tar.gz"
        dest: "{{ ansible_env.HOME }}/.local/bin"
        remote_src: true
        extra_opts:
          - '--strip-components=1'
        include:
          - "bin/unison"
    - name: Set unison binary package path
      ansible.builtin.set_fact:
        package_unison_bin: "{{ ansible_env.HOME }}/.local/bin/unison"
  when:
    - ansible_architecture == "x86_64"

- name: Install unison for aarch64
  block:
    - name: Install unison for x86_64
      become: true
      ansible.builtin.apt:
        update_cache: true
        name:
          - unison
        state: present
    - name: Set unison binary package path
      ansible.builtin.set_fact:
        package_unison_bin: "/usr/bin/unison"
  when:
    - ansible_architecture == "aarch64"
    - ansible_distribution == "Debian"

