---
- name: Install git for Debian
  block:
    - name: Install git for Debian
      become: true
      ansible.builtin.apt:
        update_cache: true
        name:
          - git
        state: present
  when:
    - ansible_distribution == "Debian"
