---
- name: Set facts
  ansible.builtin.set_fact:
    zettelkasten_restic_repo_replica_dir: "{{ replica_drive_mount_point }}/restic/zettelkasten.git"

- name: Check if restic repository exists
  ansible.builtin.command: "{{ server_bins['restic'] }} --repo {{ zettelkasten_restic_repo_replica_dir }} cat config"
  environment:
    RESTIC_PASSWORD: "{{ restic_password }}"
  ignore_errors: true
  register: restic_check

- name: Initialize restic repository
  when: restic_check.rc != 0  # in restic >= 0.17.0 check for exit code 10, otherwise 1
  ansible.builtin.command: "{{ server_bins['restic'] }} init --repo {{ zettelkasten_restic_repo_replica_dir }}"
  environment:
    RESTIC_PASSWORD: "{{ restic_password }}"

- name: Copy restic backup script
  ansible.builtin.template:
    src: zettelkasten-git-replica.sh
    dest: "{{ zettelkasten_restic_config_dir }}/zettelkasten-git-replica.sh"
    mode: "0700"

- name: Copy systemd timer for periodic replication
  ansible.builtin.copy:
    src: zettelkasten-git-replica.timer
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/zettelkasten-git-replica.timer"

- name: Copy systemd service for periodic replication
  ansible.builtin.template:
    src: zettelkasten-git-replica.service
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/zettelkasten-git-replica.service"

- name: Enable systemd timer for periodic replication
  ansible.builtin.systemd_service:
    name: zettelkasten-git-replica.timer
    scope: user
    enabled: true
    state: started
