---
- name: Set facts
  ansible.builtin.set_fact:
    zettelkasten_restic_repo_replica_dir: "{{ replica_drive_mount_point }}/restic/zettelkasten.git"

- name: Check if restic repository exists
  ansible.builtin.command: restic --repo "{{ zettelkasten_restic_repo_replica_dir }}" cat config
  environment:
    RESTIC_PASSWORD: "{{ restic_password }}"
  ignore_errors: true
  register: restic_check

- name: Initialize restic repository
  when: restic_check.rc == 10  # in restic >= 0.17.0 check for exit code 10, otherwise 1
  ansible.builtin.command: restic init --repo "{{ zettelkasten_restic_repo_replica_dir }}"
  environment:
    RESTIC_PASSWORD: "{{ restic_password }}"

- name: Copy restic environment variables file
  ansible.builtin.template:
    src: replica.env
    dest: "{{ zettelkasten_restic_config_dir }}/replica.env"
    mode: "0600"

- name: Copy systemd timer for periodic replication
  ansible.builtin.copy:
    src: zettelkasten-git-replica.timer
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/zettelkasten-git-replica.timer"

- name: Copy systemd service for periodic replication
  ansible.builtin.copy:
    src: zettelkasten-git-replica.service
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/zettelkasten-git-replica.service"

- name: Enable systemd timer for periodic replication
  ansible.builtin.systemd_service:
    name: zettelkasten-git-replica.timer
    scope: user
    enabled: true
    state: started
