---
# Based on https://git-scm.com/book/en/v2/Git-on-the-Server-Setting-Up-the-Server
- name: Create git user
  become: true
  ansible.builtin.user:
    name: git
    shell: /usr/bin/git-shell

- name: Make /home/git/.ssh
  become: true
  ansible.builtin.file:
    path: "/home/git/.ssh"
    state: directory
    mode: "0700"
    owner: git
    group: git

- name: Make authorized_keys
  become: true
  ansible.builtin.file:
    path: "/home/git/.ssh/authorized_keys"
    state: touch
    mode: "0600"
    owner: git
    group: git
    modification_time: preserve
    access_time: preserve
