---
- name: Install fzf for x86_64
  ansible.builtin.unarchive:
    src: "https://github.com/junegunn/fzf/releases/download/{{ version.fzf }}/fzf-{{ version.fzf }}-linux_amd64.tar.gz"
    dest: "{{ ansible_env.HOME }}/.local/bin"
    remote_src: true
    include:
      - "fzf"
