---
- name: Install caddy server
  ansible.builtin.get_url:
    url: "https://caddyserver.com/api/download?os=linux&arch=arm64"
    dest: "{{ ansible_env.HOME }}/.local/bin/caddy"
    force: false
    mode: 0755

- name: Create caddy directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/caddy"
    state: directory

- name: Copy Caddyfile
  ansible.builtin.copy:
    src: Caddyfile
    dest: "{{ ansible_env.HOME }}/caddy/Caddyfile"

- name: Copy systemd caddy.service
  ansible.builtin.template:
    src: caddy.service
    dest: "{{ ansible_env.HOME}}/.config/systemd/user/caddy.service"

- name: Enable systemd caddy.service
  ansible.builtin.systemd_service:
    name: caddy.service
    scope: user
    state: started
